"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.reonToJsonString = exports.reonToJson = exports.jsonStringToReon = exports.jsonToReon = void 0;

var _toReon = _interopRequireDefault(require("./to-reon.js"));

var _fromReon = _interopRequireDefault(require("./from-reon.js"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

// Generated by CoffeeScript 2.5.1
var jsonToReon = function jsonToReon(json) {
  return (0, _toReon["default"])(json);
};

exports.jsonToReon = jsonToReon;

var jsonStringToReon = function jsonStringToReon(json) {
  return (0, _toReon["default"])(JSON.parse(json));
};

exports.jsonStringToReon = jsonStringToReon;

var reonToJson = function reonToJson(reon) {
  return JSON.parse((0, _fromReon["default"])(reon));
};

exports.reonToJson = reonToJson;

var reonToJsonString = function reonToJsonString(reon) {
  return (0, _fromReon["default"])(reon);
};

exports.reonToJsonString = reonToJsonString;